version: '3.8'
services:
  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - "./env/production.env"
  frontend:
    stdin_open: true 
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    tty: true 
    depends_on:
      - backend
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:8080'
    depends_on:
      - frontend
      - backend
